import { Material } from "./types";

export const Materials: { [key: string]: Material } = {
  ROAD: {
    name: "Road",
    color: "black",
    stiffness: 1,
    durability: 2000,
    collideWithCar: true,
    lengthPenaltyFactor: 0.45,
    pricePerUnit: 2,
  },
  STEEL: {
    name: "Steel",
    color: "gray",
    stiffness: 1,
    durability: 3000,
    lengthPenaltyFactor: 0.4,
    pricePerUnit: 3,
  },
  WOOD: {
    name: "Wood",
    color: "brown",
    stiffness: 0.2,
    durability: 2000,
    lengthPenaltyFactor: 0.5,
    pricePerUnit: 1,
  },
  GRASS: {
    name: "Grass",
    color: "green",
    stiffness: 0,
    durability: 0,
    lengthPenaltyFactor: 0,
    pricePerUnit: 0,
  },
  WATER: {
    name: "Water",
    color: "blue",
    stiffness: 0,
    durability: 0,
    lengthPenaltyFactor: 0,
    pricePerUnit: 0,
    gradientColors: ["#0089D9", "#030166"],
    sensorForCar: true,
  },
  INVISIBLE: {
    name: "Invisible",
    color: "transparent",
    stiffness: 0,
    durability: 0,
    lengthPenaltyFactor: 0,
    pricePerUnit: 0,
  },
};
